# This is a template of each workflow that will be included
# in the data-reduction section of the configuration.
name:
reference:
preprocess:
postprocess:
output:
new-input: # ADD|APPEND|REPLACE|SKIP
new-result: # ADD|APPEND|REPLACE|SKIP
save: # true/false
