# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: REUSABLE-TEST

on:
  workflow_call:
    inputs:
      os-variant:
        default: 'ubuntu-20.04'
        type: string
      build-config:
        default: 'dev-env'
        type: string
      python-version:
        default: '3.9'
        type: string
      coverage-report:
        default: false
        type: boolean

jobs:
  test:
    name: tests ${{ inputs.os-variant }}, py${{ inputs.python-version }}
    runs-on: ${{ inputs.os-variant }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: tox -e test
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.coverage-report }}
        with:
          name: CoverageReport
          path: coverage_html/
